//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public Agent()
        {
            this.Application = new HashSet<Application>();
            this.SalePoint = new HashSet<SalePoint>();
        }
    
        public int AgentId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string LegalAddress { get; set; }
        public int Priority { get; set; }
        public string Principal { get; set; }
        public string TIN { get; set; }
        public string KPP { get; set; }
        public Nullable<double> TotalImplementation { get; set; }
        public int CompanyTypeId { get; set; }
    
        public virtual CompanyType CompanyType { get; set; }
        public virtual ICollection<Application> Application { get; set; }
        public virtual ICollection<SalePoint> SalePoint { get; set; }
    }
}
