//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationStatus
    {
        public ApplicationStatus()
        {
            this.Application = new HashSet<Application>();
        }
    
        public int ApplicationStatusId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Application> Application { get; set; }
    }
}
