//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.ProductApplication = new HashSet<ProductApplication>();
        }
    
        public int ApplicationId { get; set; }
        public int ManagerId { get; set; }
        public int AgentId { get; set; }
        public System.DateTime CreatingStartDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public int ApplicationStatusId { get; set; }
        public bool PrepaymentIsMade { get; set; }
        public double SummaryCost { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual ApplicationStatus ApplicationStatus { get; set; }
        public virtual ICollection<ProductApplication> ProductApplication { get; set; }
    }
}
