//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyType
    {
        public CompanyType()
        {
            this.Agent = new HashSet<Agent>();
            this.Supplier = new HashSet<Supplier>();
        }
    
        public int CompanyTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Agent> Agent { get; set; }
        public virtual ICollection<Supplier> Supplier { get; set; }
    }
}
