//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoAppDbEntities : DbContext
    {
        public DemoAppDbEntities()
            : base("name=DemoAppDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<ApplicationStatus> ApplicationStatus { get; set; }
        public virtual DbSet<CompanyType> CompanyType { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeMovement> EmployeeMovement { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentMaster> EquipmentMaster { get; set; }
        public virtual DbSet<EquipmentState> EquipmentState { get; set; }
        public virtual DbSet<Manufacture> Manufacture { get; set; }
        public virtual DbSet<ManufactureMaterial> ManufactureMaterial { get; set; }
        public virtual DbSet<Master> Master { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialHistory> MaterialHistory { get; set; }
        public virtual DbSet<MaterialType> MaterialType { get; set; }
        public virtual DbSet<MovementType> MovementType { get; set; }
        public virtual DbSet<OperationType> OperationType { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<PriceHistory> PriceHistory { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductApplication> ProductApplication { get; set; }
        public virtual DbSet<ProductStandart> ProductStandart { get; set; }
        public virtual DbSet<ProductType> ProductType { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<SaleHistory> SaleHistory { get; set; }
        public virtual DbSet<SalePoint> SalePoint { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<UnitType> UnitType { get; set; }
        public virtual DbSet<Workshop> Workshop { get; set; }
    }
}
