//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentMaster
    {
        public int EquipmentMasterId { get; set; }
        public int EquipmentId { get; set; }
        public int MasterId { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual Master Master { get; set; }
    }
}
