//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManufactureMaterial
    {
        public int ManufactureMaterialId { get; set; }
        public int ManufactureId { get; set; }
        public int MaterialId { get; set; }
    
        public virtual Manufacture Manufacture { get; set; }
        public virtual Material Material { get; set; }
    }
}
