//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Manufacture = new HashSet<Manufacture>();
            this.PriceHistory = new HashSet<PriceHistory>();
            this.ProductApplication = new HashSet<ProductApplication>();
            this.SaleHistory = new HashSet<SaleHistory>();
        }
    
        public int ProductId { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public int ProductTypeId { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
        public double MinimalCost { get; set; }
        public string PackageSize { get; set; }
        public Nullable<double> WeightOfProduct { get; set; }
        public Nullable<double> WeightWithPackage { get; set; }
        public Nullable<int> ProductStandartId { get; set; }
        public string CertificatePicture { get; set; }
    
        public virtual ICollection<Manufacture> Manufacture { get; set; }
        public virtual ICollection<PriceHistory> PriceHistory { get; set; }
        public virtual ProductStandart ProductStandart { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual ICollection<ProductApplication> ProductApplication { get; set; }
        public virtual ICollection<SaleHistory> SaleHistory { get; set; }
    }
}
