//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleHistory
    {
        public int SaleHistoryId { get; set; }
        public int ProductId { get; set; }
        public int AgentId { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public double SummaryCost { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
