//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int SupplierId { get; set; }
        public string Name { get; set; }
        public string TIN { get; set; }
        public int CompanyTypeId { get; set; }
        public int MaterialHistoryId { get; set; }
    
        public virtual CompanyType CompanyType { get; set; }
        public virtual MaterialHistory MaterialHistory { get; set; }
    }
}
